
server.port=8081
spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/faro_del_mar_db
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true